[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.backups:backups.py:116 Creating backup
[32mINFO    [0m integration.backups:backups.py:120 Creating test data 1
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.backups:backups.py:136 Creating test data 2
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.backups:backups.py:148 Scaling down to 1 unit
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql (waiting for exactly 1 units, current : 3)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql (waiting for exactly 1 units, current : 2)
[32mINFO    [0m integration.backups:backups.py:158 Restoring backup 2025-05-04T01:35:53Z with bad restore-to-time parameter
[32mINFO    [0m integration.backups:backups.py:167 Restoring backup 2025-05-04T01:35:53Z with year_before restore-to-time parameter
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/1 [executing] active: Primary
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.backups:backups.py:179 Restoring backup 2025-05-04T01:35:53Z with year_after restore-to-time parameter
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/1 [executing] active: Primary
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.backups:backups.py:191 Restoring backup 2025-05-04T01:35:53Z with actual restore-to-time parameter
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/1 [executing] active: Primary
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.backups:backups.py:203 Restoring backup 2025-05-04T01:35:53Z with restore-to-time=latest parameter
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/1 [idle] active: Primary
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.backups:backups.py:38 Cleaning backups from cloud buckets
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.5    unsupported  01:40:22Z

App            Version          Status   Scale  Charm          Channel        Rev  Exposed  Message
mysql          8.0.41-0ubun...  blocked      1  mysql                           0  no       Move restored cluster to another S3 repository
s3-integrator                   active       1  s3-integrator  latest/stable  145  no       

Unit              Workload  Agent  Machine  Public address  Ports           Message
mysql/1*          active    idle   2        10.121.128.67   3306,33060/tcp  Primary
s3-integrator/0*  active    idle   0        10.121.128.82                   

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.121.128.82  juju-b19b55-0  ubuntu@22.04      Running
2        started  10.121.128.67  juju-b19b55-2  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:30:43 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:30:43 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-s3-integrator-0: 01:30:43 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:32:28 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:32:28 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:32:28 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:32:36 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:32:36 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:32:36 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:32:41 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:32:41 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:32:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-2: 01:33:28 ERROR unit.mysql/2.juju-log ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/snap/charmed-mysql/common/var/run/mysqld/mysqld.sock' (2)
unit-mysql-2: 01:33:28 ERROR unit.mysql/2.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 3363, in check_mysqlcli_connection
    self._run_mysqlcli_script(
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 855, in _run_mysqlcli_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 860, in _run_mysqlcli_script
    stdout = subprocess.check_output(command, timeout=timeout, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysql', '-u', 'root', '-N', '-B', '--socket=/var/snap/charmed-mysql/common/var/run/mysqld/mysqld.sock', '-e', 'SELECT 1']' returned non-zero exit status 1.
unit-mysql-2: 01:33:28 ERROR unit.mysql/2.juju-log Failed to connect to MySQL with mysqlcli with default root user

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...