[32mINFO    [0m integration.high_availability.conftest:conftest.py:29 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:32 Starting continuous writes
[32mINFO    [0m integration.high_availability.test_upgrade_rollback_incompat:test_upgrade_rollback_incompat.py:164 Get leader unit
[32mINFO    [0m integration.high_availability.test_upgrade_rollback_incompat:test_upgrade_rollback_incompat.py:170 Run pre-upgrade-check action
[32mINFO    [0m integration.high_availability.test_upgrade_rollback_incompat:test_upgrade_rollback_incompat.py:174 Refresh with previous charm
[32mINFO    [0m integration.high_availability.test_upgrade_rollback_incompat:test_upgrade_rollback_incompat.py:177 Wait for upgrade to start
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] waiting: other units upgrading first...
  mysql/1 [idle] blocked: ready to rollback application
  mysql/2 [idle] blocked: upgrade failed. Check logs for rollback instruction
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] waiting: other units upgrading first...
  mysql/1 [idle] waiting: other units upgrading first...
  mysql/2 [executing] maintenance: starting services...
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] waiting: other units upgrading first...
  mysql/1 [idle] waiting: other units upgrading first...
  mysql/2 [executing] maintenance: starting services...
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] waiting: other units upgrading first...
  mysql/1 [idle] waiting: other units upgrading first...
  mysql/2 [executing] maintenance: starting services...
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] waiting: other units upgrading first...
  mysql/1 [idle] waiting: other units upgrading first...
  mysql/2 [executing] maintenance: starting services...
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] waiting: other units upgrading first...
  mysql/1 [idle] waiting: other units upgrading first...
  mysql/2 [executing] maintenance: starting services...
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] waiting: other units upgrading first...
  mysql/1 [idle] waiting: other units upgrading first...
  mysql/2 [executing] maintenance: joining the cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] maintenance: starting services...
  mysql/1 [idle] waiting: other units upgrading first...
  mysql/2 [idle] maintenance: upgrade completed
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] active: 
  mysql/1 [idle] active: 
  mysql/2 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] active: 
  mysql/1 [idle] active: 
  mysql/2 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/2 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] active: 
  mysql/1 [idle] active: 
  mysql/2 [executing] active: 
[32mINFO    [0m integration.high_availability.test_upgrade_rollback_incompat:test_upgrade_rollback_incompat.py:184 Ensure rollback has taken place
[32mINFO    [0m integration.high_availability.test_upgrade_rollback_incompat:test_upgrade_rollback_incompat.py:204 Ensure continuous_writes after rollback procedure
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:341 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:481 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:366 max_written_value=566 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:366 max_written_value=586 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:366 max_written_value=586 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:366 max_written_value=605 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:366 max_written_value=605 on unit mysql/2
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:366 max_written_value=625 on unit mysql/2
[32mINFO    [0m integration.high_availability.conftest:conftest.py:37 Clearing continuous writes
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.8    unsupported  01:50:17Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.34-0ubun...  active      3  mysql                          1  no       
mysql-test-app  0.0.2            active      1  mysql-test-app  latest/edge   82  no       Last written value=598

Unit               Workload  Agent  Machine  Public address  Ports           Message
mysql-test-app/0*  active    idle   3        10.228.161.106                  Last written value=598
mysql/0            active    idle   0        10.228.161.44   3306,33060/tcp  
mysql/1*           active    idle   1        10.228.161.71   3306,33060/tcp  
mysql/2            active    idle   2        10.228.161.210  3306,33060/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.228.161.44   juju-6c4901-0  ubuntu@22.04      Running
1        started  10.228.161.71   juju-6c4901-1  ubuntu@22.04      Running
2        started  10.228.161.210  juju-6c4901-2  ubuntu@22.04      Running
3        started  10.228.161.106  juju-6c4901-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-1: 01:36:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:36:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:36:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-1: 01:38:13 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
machine-3: 01:38:25 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:38:25 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:38:25 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:38:43 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:38:43 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:38:43 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:38:53 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:38:53 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:38:53 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-1: 01:39:17 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-1: 01:39:21 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-1: 01:39:35 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-0: 01:39:37 ERROR unit.mysql/0.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-1: 01:39:45 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-1: 01:39:49 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-1: 01:40:03 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-0: 01:40:05 ERROR unit.mysql/0.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-2: 01:40:07 ERROR unit.mysql/2.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-1: 01:40:12 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-0: 01:40:15 ERROR unit.mysql/0.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-1: 01:40:26 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-2: 01:40:32 ERROR unit.mysql/2.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-0: 01:40:34 ERROR unit.mysql/0.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-0: 01:40:36 ERROR unit.mysql/0.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-1: 01:40:37 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-1: 01:40:39 ERROR unit.mysql/1.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-2: 01:40:41 ERROR unit.mysql/2.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-2: 01:42:57 CRITICAL unit.mysql/2.juju-log upgrade:1: Upgrade failed, follow the instructions below to rollback:
    1. Re-run `pre-upgrade-check` action on the leader unit to enter 'recovery' state
    2. Run `juju refresh` to the previously deployed charm revision or local charm file
unit-mysql-2: 01:46:03 ERROR unit.mysql/2.juju-log upgrade:1: Failed to start mysqld
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 667, in start_mysqld
    self.wait_until_mysql_connection()
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 429, in wait_until_mysql_connection
    raise MySQLServiceNotRunningError("MySQL socket file not found")
charms.mysql.v0.mysql.MySQLServiceNotRunningError: MySQL socket file not found
unit-mysql-2: 01:46:07 ERROR unit.mysql/2.juju-log upgrade:1: Failed to uninstall MySQL on attempt=1
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 667, in start_mysqld
    self.wait_until_mysql_connection()
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 429, in wait_until_mysql_connection
    raise MySQLServiceNotRunningError("MySQL socket file not found")
charms.mysql.v0.mysql.MySQLServiceNotRunningError: MySQL socket file not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/upgrade.py", line 195, in _on_upgrade_granted
    self.charm._mysql.start_mysqld()
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 675, in start_mysqld
    raise MySQLStartMySQLDError(e.message)
charms.mysql.v0.mysql.MySQLStartMySQLDError: MySQL socket file not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 240, in uninstall_mysql
    subprocess.run(["snap", "remove", "charmed-mysql"], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snap', 'remove', 'charmed-mysql']' returned non-zero exit status 1.
unit-mysql-0: 01:47:38 ERROR unit.mysql/0.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event
unit-mysql-2: 01:49:26 ERROR unit.mysql/2.juju-log database-peers:0: Failed to reconcile binlogs collection during peer relation event

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...