[32mINFO    [0m integration.high_availability.test_upgrade_skip_pre_upgrade_check:test_upgrade_skip_pre_upgrade_check.py:98 Refresh the charm back to stable channel
[32mINFO    [0m integration.high_availability.test_upgrade_skip_pre_upgrade_check:test_upgrade_skip_pre_upgrade_check.py:105 Wait (120s) for rolling restart OR continue to writes
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:343 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:486 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:368 max_written_value=5938 on unit mysql/2
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:368 max_written_value=5940 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:368 max_written_value=5943 on unit mysql/1
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.6.2    unsupported  01:39:41Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.39-0ubun...  active      3  mysql           8.0/stable   313  no       
mysql-test-app  0.0.2            active      1  mysql-test-app  latest/edge   63  no       

Unit               Workload  Agent  Machine  Public address  Ports           Message
mysql-test-app/0*  active    idle   3        10.16.22.37                     
mysql/0            active    idle   0        10.16.22.74     3306,33060/tcp  
mysql/1*           active    idle   1        10.16.22.34     3306,33060/tcp  Primary
mysql/2            active    idle   2        10.16.22.38     3306,33060/tcp  

Machine  State    Address      Inst id        Base          AZ  Message
0        started  10.16.22.74  juju-723872-0  ubuntu@22.04      Running
1        started  10.16.22.34  juju-723872-1  ubuntu@22.04      Running
2        started  10.16.22.38  juju-723872-2  ubuntu@22.04      Running
3        started  10.16.22.37  juju-723872-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

machine-3: 01:32:02 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:32:02 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:32:03 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:32:03 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:32:03 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:32:03 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:32:07 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:32:07 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:32:07 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:32:11 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:32:11 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:32:11 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-2: 01:35:40 ERROR unit.mysql/2.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-1: 01:35:40 ERROR unit.mysql/1.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-0: 01:35:40 ERROR unit.mysql/0.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-1: 01:35:42 ERROR unit.mysql/1.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 745, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-723872-1.lxd:33062', '--python', '-c', 'shell.options.set(\'useWizards\', False)\nprint(\'###\')\nsession.run_sql("SET GLOBAL loose-audit_log_filter=OFF")']' returned non-zero exit status 1.
unit-mysql-1: 01:35:42 ERROR unit.mysql/1.juju-log Failed to set variable='loose-audit_log_filter' to value='OFF'
unit-mysql-1: 01:35:42 ERROR unit.mysql/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 745, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-723872-1.lxd:33062', '--python', '-c', 'shell.options.set(\'useWizards\', False)\nprint(\'###\')\nsession.run_sql("SET GLOBAL loose-audit_log_filter=OFF")']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 1434, in set_dynamic_variable
    self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 760, in _run_mysqlsh_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 880, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/charm.py", line 328, in _on_config_changed
    self._mysql.set_dynamic_variable(config, new_config_dict[config])
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 1442, in set_dynamic_variable
    raise MySQLSetVariableError
charms.mysql.v0.mysql.MySQLSetVariableError
unit-mysql-2: 01:35:42 ERROR unit.mysql/2.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 745, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-723872-2.lxd:33062', '--python', '-c', 'shell.options.set(\'useWizards\', False)\nprint(\'###\')\nsession.run_sql("SET GLOBAL loose-audit_log_filter=OFF")']' returned non-zero exit status 1.
unit-mysql-2: 01:35:42 ERROR unit.mysql/2.juju-log Failed to set variable='loose-audit_log_filter' to value='OFF'
unit-mysql-2: 01:35:42 ERROR unit.mysql/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 745, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-723872-2.lxd:33062', '--python', '-c', 'shell.options.set(\'useWizards\', False)\nprint(\'###\')\nsession.run_sql("SET GLOBAL loose-audit_log_filter=OFF")']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 1434, in set_dynamic_variable
    self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 760, in _run_mysqlsh_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 880, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/charm.py", line 328, in _on_config_changed
    self._mysql.set_dynamic_variable(config, new_config_dict[config])
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 1442, in set_dynamic_variable
    raise MySQLSetVariableError
charms.mysql.v0.mysql.MySQLSetVariableError
unit-mysql-0: 01:35:42 ERROR unit.mysql/0.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 745, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-723872-0.lxd:33062', '--python', '-c', 'shell.options.set(\'useWizards\', False)\nprint(\'###\')\nsession.run_sql("SET GLOBAL loose-audit_log_filter=OFF")']' returned non-zero exit status 1.
unit-mysql-0: 01:35:42 ERROR unit.mysql/0.juju-log Failed to set variable='loose-audit_log_filter' to value='OFF'
unit-mysql-0: 01:35:42 ERROR unit.mysql/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 745, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-723872-0.lxd:33062', '--python', '-c', 'shell.options.set(\'useWizards\', False)\nprint(\'###\')\nsession.run_sql("SET GLOBAL loose-audit_log_filter=OFF")']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/mysql.py", line 1434, in set_dynamic_variable
    self._run_mysqlsh_script(
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 760, in _run_mysqlsh_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/charm.py", line 880, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/charm.py", line 328, in _on_config_changed
    self._mysql.set_dynamic_variable(config, new_config_dict[config])
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/mysql.py", line 1442, in set_dynamic_variable
    raise MySQLSetVariableError
charms.mysql.v0.mysql.MySQLSetVariableError
unit-mysql-1: 01:35:42 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-2: 01:35:43 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-0: 01:35:43 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-0: 01:37:49 ERROR unit.mysql/0.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-2: 01:37:49 ERROR unit.mysql/2.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-1: 01:37:49 ERROR unit.mysql/1.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...