[32mINFO    [0m integration.high_availability.conftest:conftest.py:23 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:26 Starting continuous writes
[32mINFO    [0m integration.helpers:helpers.py:481 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:356 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:481 Retrieving primary unit
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:391 Stopping server on unit mysql/2
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:394 Removing data directory
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:410 Purge binlogs on unit mysql/0
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:410 Purge binlogs on unit mysql/1
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:418 Waiting unit to enter in maintenance.
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:425 Waiting unit to be back online.
[32mINFO    [0m integration.helpers:helpers.py:481 Retrieving primary unit
[32mINFO    [0m integration.high_availability.test_self_healing:test_self_healing.py:437 Check if instance in cluster
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:356 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:481 Retrieving primary unit
[32mINFO    [0m integration.helpers:helpers.py:481 Retrieving primary unit
[32mINFO    [0m integration.helpers:helpers.py:481 Retrieving primary unit
[32mINFO    [0m integration.high_availability.conftest:conftest.py:31 Clearing continuous writes
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.4    unsupported  01:55:46Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.37-0ubun...  active      3  mysql                          0  no       
mysql-test-app  0.0.2            active      1  mysql-test-app  latest/edge   46  no       

Unit               Workload  Agent  Machine  Public address  Ports           Message
mysql-test-app/0*  active    idle   3        10.42.134.117                   
mysql/0            active    idle   0        10.42.134.226                   
mysql/1*           active    idle   1        10.42.134.221   3306,33060/tcp  Primary
mysql/2            active    idle   2        10.42.134.194   3306,33060/tcp  

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.42.134.226  juju-75fa13-0  ubuntu@22.04      Running
1        started  10.42.134.221  juju-75fa13-1  ubuntu@22.04      Running
2        started  10.42.134.194  juju-75fa13-2  ubuntu@22.04      Running
3        started  10.42.134.117  juju-75fa13-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

machine-1: 01:36:40 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:36:40 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:36:40 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:36:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:36:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:36:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:36:43 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:36:43 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:36:44 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:40:15 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:40:15 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:40:15 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-0: 01:41:51 ERROR unit.mysql/0.juju-log Failed to get cluster status for test_cluster
unit-mysql-0: 01:41:59 ERROR unit.mysql/0.juju-log Failed to get cluster status for test_cluster
unit-mysql-1: 01:42:05 ERROR unit.mysql/1.juju-log Failed to get cluster status for test_cluster
unit-mysql-1: 01:42:05 ERROR unit.mysql/1.juju-log Failed to get cluster members
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/relations/mysql_provider.py", line 161, in _update_endpoints
    rw_endpoints, ro_endpoints, _ = self.charm._mysql.get_cluster_endpoints()
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 1743, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-0: 01:42:07 ERROR unit.mysql/0.juju-log Failed to get cluster status for test_cluster
unit-mysql-1: 01:42:16 ERROR unit.mysql/1.juju-log Failed to get cluster status for test_cluster
unit-mysql-1: 01:42:16 ERROR unit.mysql/1.juju-log Failed to get cluster members
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/relations/mysql_provider.py", line 161, in _update_endpoints
    rw_endpoints, ro_endpoints, _ = self.charm._mysql.get_cluster_endpoints()
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 1743, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
machine-2: 01:45:13 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
machine-2: 01:45:16 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [386d1d] "machine-2" cannot open api: unable to connect to API: dial tcp 10.42.134.5:17070: connect: network is unreachable
unit-mysql-1: 01:51:44 ERROR unit.mysql/1.juju-log Failed to get cluster status for test_cluster
unit-mysql-1: 01:51:44 ERROR unit.mysql/1.juju-log Failed to get cluster members
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/relations/mysql_provider.py", line 161, in _update_endpoints
    rw_endpoints, ro_endpoints, _ = self.charm._mysql.get_cluster_endpoints()
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 1743, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-2: 01:54:08 ERROR unit.mysql/2.juju-log Failed to flush ERROR LOGS logs.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 713, in _run_mysqlsh_script
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--no-wizard', '--python', '-f', '/var/snap/charmed-mysql/common/tmpd5_2chgn']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 2817, in flush_mysql_logs
    self._run_mysqlsh_script("\n".join(flush_logs_commands), timeout=50)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 717, in _run_mysqlsh_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError
unit-mysql-2: 01:54:27 ERROR unit.mysql/2.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-2: 01:54:37 ERROR unit.mysql/2.juju-log Failed to get member state: mysqld daemon is down
unit-mysql-2: 01:54:47 ERROR unit.mysql/2.juju-log Failed to get member state: mysqld daemon is down

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...